### ISSUE TITLE
enry-java fails on macOS Mojave

### ISSUE THREAD

**Issue by smacker** [src-d/enry#191]
With dylib from the last release it fails with `Trace/BPT trap: 5`.

```
$ make test
./sbt clean test
[info] Loading project definition from /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to enry-java (in build file:/Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/)
[success] Total time: 0 s, completed Jan 23, 2019 12:31:29 PM
[info] Updating {file:/Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/}java...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 3 Java sources to /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/target/classes...
[info] Packaging /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/target/enry-java-1.6.8-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Java source to /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/target/test-classes...
[info] Packaging /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/target/enry-java-1.6.8-SNAPSHOT-tests.jar ...
[info] Done packaging.
make: *** [test] Trace/BPT trap: 5
```

If I build dylib locally on Mojave it works.

**Comment by creachadair** [comment]
Just to verify: By "latest release" you mean https://github.com/src-d/enry/releases/tag/v1.6.7?

**Comment by creachadair** [comment]
Apparently I should finish reading my open threads; this was addressed by #190.

**Comment by smacker** [comment]
@creachadair it's not fixed. I closed the PR because it doesn't work and opened this issue. Please reopen it.

**Comment by creachadair** [comment]
> @creachadair it's not fixed. I closed the PR because it doesn't work and opened this issue. Please reopen it.

Oops! Done, sorry.

**Comment by bzz** [comment]
Thank you guys for logging this in.
Will look into fixing this as soon as I got my hands on machine/VM with Mojave in order to be able to reproduce.

**Comment by smacker** [comment]
I tried to rebuild enry using new [10.14.3 beta image](https://travis-ci.org/smacker/enry/jobs/494031244#L6) on travis but it still crashes.

Full log: https://gist.github.com/smacker/515f1853cca80076a5358b2db9c70b5c

On multiple runs diffrent threads with different instructions are crashing.

Another interesting thing is the output of `./sbt test`:
```
$ ./sbt test
[info] Loading project definition from /Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to enry-java (in build file:/Users/smacker/go/src/gopkg.in/src-d/enry.v1/java/)
[info] Passed: Total 19, Failed 0, Errors 0, Passed 19
Trace/BPT trap: 5
```

it shows that all tests passed. So most probably it's related to some finilizer maybe?

**Comment by smacker** [comment]
It works with [this dynlib](https://github.com/smacker/enry/releases/download/v0.7.2/libenry.dylib) from v0.7.2 here: https://github.com/smacker/enry/releases
The only change from before go 1.11.

But enry unit tests fail on 1.11: https://travis-ci.org/smacker/enry/jobs/494060589
the generator part.

**Comment by bzz** [comment]
Going to cut a new release of enry-java using go 1.11 as it seem to resolve the issue with newer macOS.

**Comment by bzz** [comment]
@smacker could you please double-check if java tests passes on macOS Mojave with native lib from https://github.com/bzz/enry/releases/tag/cross-go-11-mojave ?

Simples way to do so is
```
cd java
make
wget https://github.com/bzz/enry/releases/download/cross-go-11-mojave/libenry.dylib
mv libenry.dylib ./shared/darwin
make test
```

**Comment by smacker** [comment]
Confirmed. It works:
```
$ ./sbt test
[info] Passed: Total 19, Failed 0, Errors 0, Passed 19
[success] Total time: 1 s, completed Feb 21, 2019 1:18:08 AM
```

**Comment by bzz** [comment]
https://github.com/src-d/enry/releases/tag/v1.7.1 was just released and landed on Maven.

Could you please try that out?

**Comment by smacker** [comment]
Works like a magic! 😍
